name: CI

permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - uses: oven-sh/setup-bun@v2
        name: Setup Bun
        with:
          bun-version: 1.1.45
      - uses: actions/cache@v4
        name: Restore Bun install cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-1.1.45-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-1.1.45-bun-
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun lint
      - name: Format check
        run: bun format:check
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun: [1.1.45, latest]

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - uses: oven-sh/setup-bun@v2
        name: Setup Bun ${{ matrix.bun }}
        with:
          bun-version: ${{ matrix.bun }}
      - uses: actions/cache@v4
        name: Restore Bun install cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-
      - name: Install dependencies
        run: bun install
      - name: Test
        run: bun test
