name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  # Test on both Node.js and Bun
  test-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x, 14.x, 16.x, 18.x, 20.x, 21.x, 22.x]

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - uses: actions/setup-node@v4
        name: Setup Node.js ${{ matrix.node }}
        with:
          node-version: ${{ matrix.node }}
      - uses: oven-sh/setup-bun@v2
        name: Setup Bun
        with:
          bun-version: 1.1.x
      - uses: actions/cache@v4
        name: Restore Bun install cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.node }}-node-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-node-
      - name: Install dependencies
        run: bun install
      - name: Test
        run: pnpm test
  test-bun:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun: [1.1.x]

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - uses: oven-sh/setup-bun@v2
        name: Setup Bun ${{ matrix.bun }}
        with:
          bun-version: ${{ matrix.bun }}
      - uses: actions/cache@v4
        name: Restore Bun install cache
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-
      - name: Install dependencies
        run: bun install
      - name: Test
        run: bun test
