name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x, 14.x, 15.x]

        steps:
            - uses: actions/checkout@v2
              name: Checkout repository
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
            - uses: actions/cache@v2
              id: yarn-cache
              name: Cache yarn directory
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            - uses: borales/actions-yarn@v2.0.0
              name: Run yarn install
              with:
                  cmd: install
            - uses: borales/actions-yarn@v2.0.0
              name: Test
              with:
                  cmd: test
